# Generated by Django 5.1.7 on 2025-06-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
